socketcan_to_topic_node:
  ros__parameters:
    can_device: "vcan0"
    json_file: "/home/ros2/foxy/deepx/json_example.json"

topic_to_socketcan_node:
  ros__parameters:
    can_device: "vcan0"
    json_file: "/home/ros2/foxy/deepx/json_example.json"
